### ISSUE TITLE
Batch size of 100 crashes on 0.2.0

### ISSUE THREAD

**Issue by rlt** [buildkite/test_collector_elixir#7]
Hello, in reference to issue https://github.com/buildkite/test_collector_elixir/issues/3

I am using 0.2.0. It crashed for me with the new batch size of 100. A batch size of 50 stops the crashing, however I see no results on the dashboard and there is no error in the build log. I am running on Github Actions.

**Comment by jimsynz** [comment]
Thanks @rlt. I just had a scroll through https://github.com/elixir-tesla/tesla/issues/394 and I think the best solution is that we switch out the tesla backend in this library.  We chose mint because we wanted the HTTP2 support, but if it's not working correctly then it's not worth the trouble.  Watch this space.
